#!/usr/bin/env python
import argparse

from botocore.session import get_session
from s3transfer.manager import TransferManager


class NonSeekableReader(object):
    def __init__(self, fileobj):
        self._fileobj = fileobj

    def read(self, amt=-1):
        return self._fileobj.read(amt)


class Uploader(object):
    def upload(self, args):
        session = get_session()
        client = session.create_client('s3')
        file_type = args.file_type
        with TransferManager(client) as manager:
            getattr(self, 'upload_' + file_type)(
                manager, args.file_name, args.s3_bucket, args.s3_key)

    def upload_filename(self, manager, filename, bucket, s3_key):
        manager.upload(filename, bucket, s3_key)

    def upload_seekable(self, manager, filename, bucket, s3_key):
        with open(filename, 'rb') as f:
            future = manager.upload(f, bucket, s3_key)
            future.result()

    def upload_nonseekable(self, manager, filename, bucket, s3_key):
        with open(filename, 'rb') as f:
            future = manager.upload(
                NonSeekableReader(f), bucket, s3_key)
            future.result()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--file-name', required=True)
    parser.add_argument(
        '--file-type', choices=['filename', 'seekable', 'nonseekable'],
        required=True)
    parser.add_argument('--s3-bucket', required=True)
    parser.add_argument('--s3-key', required=True)
    args = parser.parse_args()
    Uploader().upload(args)


if __name__ == '__main__':
    main()
